### ISSUE TITLE
JavaEE Test Server

### ISSUE THREAD

**Issue by bradyshutt** [cpe305/fall2016-project-bradyshutt#3]
The project will be ran on a JavaEE server. Put together a test server with the JavaEE packages that simply reads an HTTP request, and logs the request to the console.

**Comment by dsabsay** [comment]
Found some links that may be helpful in doing this:
http://niklasschlimm.blogspot.com/2011/06/setting-up-java-ee-6-development.html
(For Eclipse)

http://docs.oracle.com/javaee/6/firstcup/doc/gcrkp.html
(For NetBeans)
